
export const MENU_LOADING = 'MENU_LOADING';
export const ADD_MENU = 'ADD_MENU';
export const MENU_FAILED = 'MENU_FAILED';
export const MENUITEMS_LOADING = 'MENUITEMS_LOADING';
export const ADD_MENUITMES = 'ADD_MENUITEMS';
export const MENUITEMS_FAILED = 'MENUITEMS_FAILED';

